### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Jaykah** [cloudfoundry-incubator/galera-healthcheck#1]
Hi,

I have been trying to wrap my head around the install process, but my complete unfamiliarity with go is making it quite difficult.

Would highly appreciate if you could point me in the right direction, and I will fill in the spaces in the README once I'm up and running so that others won't have to go through this nightmare :)

```
apt-get install -y golang git mercurial
cd /var && git clone https://github.com/cloudfoundry-incubator/galera-healthcheck.git
cd /var/healthcheck/Godeps/_workspace && mkdir bin pkg
export GOPATH=/var/healthcheck/Godeps/_workspace/
cd src && git clone https://github.com/kr/fs.git
hg clone https://code.google.com/p/go.tools/
mkdir -p /var/healthcheck/Godeps/_workspace/src/golang.org/x/
ln -s /var/healthcheck/Godeps/_workspace/src/go.tools /var/healthcheck/Godeps/_workspace/src/golang.org/x/tools
mkdir -p /var/healthcheck/Godeps/_workspace/src/github.com/kr
ln -s /var/healthcheck/Godeps/_workspace/src/fs /var/healthcheck/Godeps/_workspace/src/github.com/kr/fs
```

...after which I still get

```
# /var/healthcheck/bin/test
/usr/bin/go
/var/healthcheck/bin/test: 12: /var/healthcheck/bin/test: godep: not found
```

What am I doing wrong, and what are the next steps to get it up and running?

Thanks!

**Comment by robdimsdale** [comment]
Hi @Jaykah 

Apologies for not seeing this sooner. Since you opened this issue we've moved away from using godep to manage dependencies; this project is a submodule of https://github.com/cloudfoundry/cf-mysql-release and dependencies are vendored in to that.

As the original reason for opening this issue is no longer valid, can we close this?

**Comment by Jaykah** [comment]
Yes, I have solved the issue a while back, forgot to close this.

Thanks.
